spring.application.name=Puzzleteca

# Puerto del server
server.port=8080

# ===== DATOS POSTGRES =====
spring.datasource.url=jdbc:postgresql://localhost:5432/aprendizaje?currentSchema=puzzlesbbdd
spring.datasource.username=postgres
spring.datasource.password=alumno

# Driver (opcional pero recomendado)
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.tu.paquete=DEBUG

